### ISSUE TITLE
Test all Opcodes

### ISSUE THREAD

**Issue by zanderlewis** [zanderlewis/mdpu.c#1]
## Overview
Many of the Opcodes are untested and were created with the aid of Github Copilot. Help would be appreciated for testing these Opcodes so if anything needs to be fixed, it can.

**Comment by manas-02** [comment]
Hi, I am new to open-source contributions. I would like to help. Can u tell me some details.

**Comment by zanderlewis** [comment]
> Hi, I am new to open-source contributions. I would like to help. Can u tell me some details.

Hey there! Thanks for your interest in this project!

I would start by cloning the repository (and of course having a C compiler) with `git clone https://github.com/zanderlewis/mdpu.c` and looking through the code yourself and playing around with the Opcodes. I haven't tested all the Opcodes yet and the tested ones are being used in the built-in sample program.

Thanks for your interest in helping! :)

**Comment by zanderlewis** [comment]
I was able to test all the Opcodes. If you want to help out with any other parts of the project, you may :)

**Comment by manas-02** [comment]
Thank you for your response. From your repository details I came to know that it is a cpu emulator program. Yes I can help you with other parts of the project. Just let me know what should I do.
